apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: evaluation-service
data:
  REDIS_URL: "redis://togglemaster-redis-001.a3y9sg.0001.use1.cache.amazonaws.com:6379"
  FLAG_SERVICE_URL: "http://flag-service.flag-service.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.targeting-service.svc.cluster.local:8003"
  AWS_REGION: "us-east-1"
